# Generated by Django 4.1 on 2022-09-02 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0002_alter_cliente_options_alter_clienttype_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
